# 1. Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import multilabel_confusion_matrix
from tqdm import tqdm
import seaborn

# 2. Loading the Dataset

In [2]:
data = datasets.load_iris()

In [3]:
df = pd.DataFrame(data = data.data, columns = data.feature_names)

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
# data.DESCR
# data.target_names
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
df['target'] = data.target

In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [8]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145       2  
146       2  
147       2  
148       2  
149       2

# 3. Creating X and Y labels

In [9]:
x = df.drop("target", axis = 1)
y = df['target']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 101)

In [10]:
x_train.shape, y_train.shape

((120, 4), (120,))

In [11]:
x_test.shape, y_test.shape

((30, 4), (30,))

# 4. Creating a Classification Model

In [12]:
model1 = DecisionTreeClassifier()
model1.fit(x_train, y_train)
print("Score of the model is: ", model1.score(x_test, y_test))
y_pred = model1.predict(x_test)
print("Confusion matrix:")
print(multilabel_confusion_matrix(y_test, y_pred))

Score of the model is:  0.9666666666666667
Confusion matrix:
[[[20  0]
  [ 0 10]]

 [[17  1]
  [ 0 12]]

 [[22  0]
  [ 1  7]]]


In [14]:
model2 = RandomForestClassifier()
model2.fit(x_train, y_train)
print("Score of the model is: ", model2.score(x_test, y_test))
y_pred2 = model2.predict(x_test)
print("Confusion matrix:")
print(multilabel_confusion_matrix(y_test, y_pred2))

Score of the model is:  0.9333333333333333
Confusion matrix:
[[[20  0]
  [ 0 10]]

 [[16  2]
  [ 0 12]]

 [[22  0]
  [ 2  6]]]


In [16]:
print(148 / 150 * 100)

98.66666666666667
